apiVersion: v1
kind: Secret
metadata:
  # Secret for Mayan EDMS' database
  name: db-secret
data:
  # Data must use base64 encoding, i.e., `echo -n '****' | base64`
  #
  # For a production deployment, the system admin should first change
  # the `password` fields in both "mb-secret.yaml" and
  # "db-secret.yaml", make sure that these passwords are **NOT**
  # committed to git and **NOT** published to the internet.
  #
  password: bWF5YW5kYnBhc3M=
