apiVersion: v1
kind: Secret
metadata:
  # Secret for Mayan EDMS' message broker
  name: mb-secret
data:
  # Data must use base64 encode; try `echo -n '****' | base64`
  password: bWF5YW5yZWRpc3Bhc3N3b3Jk
